### ISSUE TITLE
"Invalid input"

### ISSUE THREAD

**Issue by ColinMaudry** [csalmeida/quark#5]
ProtonMail gives an `Invalid input` message when I click Save.

CSSlint.net gives warnings but the CSS is valid. I added spaces and line break before { and after }, but that didn't help.

http://pastebin.com/RjTX3fXD

**Comment by csalmeida** [comment]
Hi @ColinMaudry

I have tried your theme from [Pastebin](http://pastebin.com/RjTX3fXD) and it works okay. Do you experience this issue only using Quark or when applying other themes as well?

**Comment by ColinMaudry** [comment]
Hi!

It works now... That may be the network I was connected to yesterday, because I also got error when I tried sending emails. A public Wi-fi network.

Thanks for the reactivity, and congratulations for the tool.
