### ISSUE TITLE
What about customizing other areas?

### ISSUE THREAD

**Issue by ColinMaudry** [csalmeida/quark#6]
Hi again!

What I really would like to have, is a dark skin: with light text and dark backgrounds.

Quark lets me do this for the framing UI, but not for

- the list of emails
- the composing window

Any chance you could add that?

I had made some theming a couple of months ago, but ProtonMail CSS updates broke it quite often, so I gave up :(

**Comment by csalmeida** [comment]
Hi @ColinMaudry 

I plan to extend the tool and [add more features in the future](https://github.com/csalmeida/quark/projects/1). For now the only way of changing those elements is to add further styling to the generated theme. 

I have also published a [theme template for version 3.7.3](https://github.com/csalmeida/protonmail-themes/blob/master/Themes/v3.7.3/theme_template/template_v3.7.3.scss) written in *SCSS*. It might be worth it having a look as it's for anyone who wants to further customize themes without having to start from scratch.

ProtonMail's CSS has been changing for a while and sometimes it can be difficult to keep up. Try accessing [ProtonMail Beta](https://protonmail.com/blog/protonmail-beta/) to get a better idea which elements are about to change.

Hope this helps.
